### ISSUE TITLE
option to set contextPath override using system property

### ISSUE THREAD

**Issue by tveimo** [j-a-w-r/jawr#10]
We use different CDN hostnames for staging and production, so it would be handy to override the contextPath using a system property instead of in the jawr.properties file.

I tried using a property similar to net.jawr.debug.on but it doesn't seem to work

net.jawr.url.contextpath.override=//xxx.kxcdn.com

**Comment by ic3fox** [comment]
Hi,

Jawr provides a way to define a configuration property resolver, which must implement the interface *ConfigPropertyResolver* and which will be called to resolved properties which looks like : **${**myValueToReplace**}** 

For instance, you can have in your configuration file something like : 

```java

jawr.url.contextpath.override=${CDN.value}

```

This resolver is defined in your servlet configuration.
So here the idea is that your config property resolver will look for the right value in the system property or provide a default one if it doesn't exists.

Jawr already provide by default a property resolver which look at the property in the System properties. (*net.jawr.web.config.ConfigSystemPropertyResolver*)

Please take a look at the following link for more detail : [Defining a custom property resolver](https://jawr.java.net/docs/servlet.html#Defining_a_custom_property_resolver)  

Please let me know if this fix your issue.

Cheers,

**Comment by tveimo** [comment]
Yes this setup would work. Am wondering if the resolver class could be injected instead of specified as a class name? We use servlet config using Java only, and would like to resolve these properties using Spring managed code, so passing in an already autowired initialised class would be more elegant than using workarounds in the resolver to be able to autowire properties and other services.

**Comment by ic3fox** [comment]
Hi,

Can I contact you offline to see how we could handle this and how to improve the use of Jawr and Spring? 
Or you can contact me at : icefox.jawr@gmail.com

Cheers

**Comment by ic3fox** [comment]
Hi,

I'm considering this issue as closed.
If you would like to reopen it, please create a new issue on the Jawr main repository : 
https://github.com/j-a-w-r/jawr-main-repo/issues/

Cheers,
