### ISSUE TITLE
Vaadin compiler not working in WebSphere 8.5

### ISSUE THREAD

**Issue by jlcrow** [j-a-w-r/jawr#14]
I've tried utilizing saas in version 3.8, I've added the vaadin-sass-compiler v0.9.12 to my project. Just as a simple test I added a test.scss file to my project with a $backcolor variable and then applied the variable to a body tag to change the color. When I deploy to tomcat I see the color change, however when I point deploy the same project to WebSphere 8.5 I receive an unmodified file back from the jawr_generator.js. I don't receive any exceptions, just a css file with unmodified variable strings.

**Comment by ic3fox** [comment]
Hi,

Are you still encountering this issue?
If it's the case please open an issue on the main repository : https://github.com/j-a-w-r/jawr-main-repo/issues/

Cheers,
